// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Response.proto

package cn.edu.nju.software.fabricservice.protomsg;

public final class ResponseOuterClass {
  private ResponseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SimpleResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SimpleResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .SimpleRequest requests = 1;</code>
     */
    java.util.List<cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequest> 
        getRequestsList();
    /**
     * <code>repeated .SimpleRequest requests = 1;</code>
     */
    cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequest getRequests(int index);
    /**
     * <code>repeated .SimpleRequest requests = 1;</code>
     */
    int getRequestsCount();
    /**
     * <code>repeated .SimpleRequest requests = 1;</code>
     */
    java.util.List<? extends cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequestOrBuilder> 
        getRequestsOrBuilderList();
    /**
     * <code>repeated .SimpleRequest requests = 1;</code>
     */
    cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequestOrBuilder getRequestsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code SimpleResponse}
   */
  public  static final class SimpleResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SimpleResponse)
      SimpleResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SimpleResponse.newBuilder() to construct.
    private SimpleResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SimpleResponse() {
      requests_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SimpleResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                requests_ = new java.util.ArrayList<cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequest>();
                mutable_bitField0_ |= 0x00000001;
              }
              requests_.add(
                  input.readMessage(cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequest.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          requests_ = java.util.Collections.unmodifiableList(requests_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.internal_static_SimpleResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.internal_static_SimpleResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse.class, cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse.Builder.class);
    }

    public static final int REQUESTS_FIELD_NUMBER = 1;
    private java.util.List<cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequest> requests_;
    /**
     * <code>repeated .SimpleRequest requests = 1;</code>
     */
    public java.util.List<cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequest> getRequestsList() {
      return requests_;
    }
    /**
     * <code>repeated .SimpleRequest requests = 1;</code>
     */
    public java.util.List<? extends cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequestOrBuilder> 
        getRequestsOrBuilderList() {
      return requests_;
    }
    /**
     * <code>repeated .SimpleRequest requests = 1;</code>
     */
    public int getRequestsCount() {
      return requests_.size();
    }
    /**
     * <code>repeated .SimpleRequest requests = 1;</code>
     */
    public cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequest getRequests(int index) {
      return requests_.get(index);
    }
    /**
     * <code>repeated .SimpleRequest requests = 1;</code>
     */
    public cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequestOrBuilder getRequestsOrBuilder(
        int index) {
      return requests_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < requests_.size(); i++) {
        output.writeMessage(1, requests_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < requests_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, requests_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse)) {
        return super.equals(obj);
      }
      cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse other = (cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse) obj;

      boolean result = true;
      result = result && getRequestsList()
          .equals(other.getRequestsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRequestsCount() > 0) {
        hash = (37 * hash) + REQUESTS_FIELD_NUMBER;
        hash = (53 * hash) + getRequestsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SimpleResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SimpleResponse)
        cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.internal_static_SimpleResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.internal_static_SimpleResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse.class, cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse.Builder.class);
      }

      // Construct using cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRequestsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (requestsBuilder_ == null) {
          requests_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          requestsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.internal_static_SimpleResponse_descriptor;
      }

      public cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse getDefaultInstanceForType() {
        return cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse.getDefaultInstance();
      }

      public cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse build() {
        cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse buildPartial() {
        cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse result = new cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse(this);
        int from_bitField0_ = bitField0_;
        if (requestsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            requests_ = java.util.Collections.unmodifiableList(requests_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.requests_ = requests_;
        } else {
          result.requests_ = requestsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse) {
          return mergeFrom((cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse other) {
        if (other == cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse.getDefaultInstance()) return this;
        if (requestsBuilder_ == null) {
          if (!other.requests_.isEmpty()) {
            if (requests_.isEmpty()) {
              requests_ = other.requests_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRequestsIsMutable();
              requests_.addAll(other.requests_);
            }
            onChanged();
          }
        } else {
          if (!other.requests_.isEmpty()) {
            if (requestsBuilder_.isEmpty()) {
              requestsBuilder_.dispose();
              requestsBuilder_ = null;
              requests_ = other.requests_;
              bitField0_ = (bitField0_ & ~0x00000001);
              requestsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRequestsFieldBuilder() : null;
            } else {
              requestsBuilder_.addAllMessages(other.requests_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequest> requests_ =
        java.util.Collections.emptyList();
      private void ensureRequestsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          requests_ = new java.util.ArrayList<cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequest>(requests_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequest, cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequest.Builder, cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequestOrBuilder> requestsBuilder_;

      /**
       * <code>repeated .SimpleRequest requests = 1;</code>
       */
      public java.util.List<cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequest> getRequestsList() {
        if (requestsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(requests_);
        } else {
          return requestsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .SimpleRequest requests = 1;</code>
       */
      public int getRequestsCount() {
        if (requestsBuilder_ == null) {
          return requests_.size();
        } else {
          return requestsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .SimpleRequest requests = 1;</code>
       */
      public cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequest getRequests(int index) {
        if (requestsBuilder_ == null) {
          return requests_.get(index);
        } else {
          return requestsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .SimpleRequest requests = 1;</code>
       */
      public Builder setRequests(
          int index, cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequest value) {
        if (requestsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRequestsIsMutable();
          requests_.set(index, value);
          onChanged();
        } else {
          requestsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SimpleRequest requests = 1;</code>
       */
      public Builder setRequests(
          int index, cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequest.Builder builderForValue) {
        if (requestsBuilder_ == null) {
          ensureRequestsIsMutable();
          requests_.set(index, builderForValue.build());
          onChanged();
        } else {
          requestsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SimpleRequest requests = 1;</code>
       */
      public Builder addRequests(cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequest value) {
        if (requestsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRequestsIsMutable();
          requests_.add(value);
          onChanged();
        } else {
          requestsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .SimpleRequest requests = 1;</code>
       */
      public Builder addRequests(
          int index, cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequest value) {
        if (requestsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRequestsIsMutable();
          requests_.add(index, value);
          onChanged();
        } else {
          requestsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SimpleRequest requests = 1;</code>
       */
      public Builder addRequests(
          cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequest.Builder builderForValue) {
        if (requestsBuilder_ == null) {
          ensureRequestsIsMutable();
          requests_.add(builderForValue.build());
          onChanged();
        } else {
          requestsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SimpleRequest requests = 1;</code>
       */
      public Builder addRequests(
          int index, cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequest.Builder builderForValue) {
        if (requestsBuilder_ == null) {
          ensureRequestsIsMutable();
          requests_.add(index, builderForValue.build());
          onChanged();
        } else {
          requestsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SimpleRequest requests = 1;</code>
       */
      public Builder addAllRequests(
          java.lang.Iterable<? extends cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequest> values) {
        if (requestsBuilder_ == null) {
          ensureRequestsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, requests_);
          onChanged();
        } else {
          requestsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .SimpleRequest requests = 1;</code>
       */
      public Builder clearRequests() {
        if (requestsBuilder_ == null) {
          requests_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          requestsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .SimpleRequest requests = 1;</code>
       */
      public Builder removeRequests(int index) {
        if (requestsBuilder_ == null) {
          ensureRequestsIsMutable();
          requests_.remove(index);
          onChanged();
        } else {
          requestsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .SimpleRequest requests = 1;</code>
       */
      public cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequest.Builder getRequestsBuilder(
          int index) {
        return getRequestsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .SimpleRequest requests = 1;</code>
       */
      public cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequestOrBuilder getRequestsOrBuilder(
          int index) {
        if (requestsBuilder_ == null) {
          return requests_.get(index);  } else {
          return requestsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .SimpleRequest requests = 1;</code>
       */
      public java.util.List<? extends cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequestOrBuilder> 
           getRequestsOrBuilderList() {
        if (requestsBuilder_ != null) {
          return requestsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(requests_);
        }
      }
      /**
       * <code>repeated .SimpleRequest requests = 1;</code>
       */
      public cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequest.Builder addRequestsBuilder() {
        return getRequestsFieldBuilder().addBuilder(
            cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequest.getDefaultInstance());
      }
      /**
       * <code>repeated .SimpleRequest requests = 1;</code>
       */
      public cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequest.Builder addRequestsBuilder(
          int index) {
        return getRequestsFieldBuilder().addBuilder(
            index, cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequest.getDefaultInstance());
      }
      /**
       * <code>repeated .SimpleRequest requests = 1;</code>
       */
      public java.util.List<cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequest.Builder> 
           getRequestsBuilderList() {
        return getRequestsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequest, cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequest.Builder, cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequestOrBuilder> 
          getRequestsFieldBuilder() {
        if (requestsBuilder_ == null) {
          requestsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequest, cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequest.Builder, cn.edu.nju.software.fabricservice.protomsg.Requests.SimpleRequestOrBuilder>(
                  requests_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          requests_ = null;
        }
        return requestsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SimpleResponse)
    }

    // @@protoc_insertion_point(class_scope:SimpleResponse)
    private static final cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse();
    }

    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SimpleResponse>
        PARSER = new com.google.protobuf.AbstractParser<SimpleResponse>() {
      public SimpleResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SimpleResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SimpleResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SimpleResponse> getParserForType() {
      return PARSER;
    }

    public cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.SimpleResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 code = 1;</code>
     */
    int getCode();

    /**
     * <code>string message = 2;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>bytes data = 3;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      code_ = 0;
      message_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              code_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            case 26: {

              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.internal_static_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.internal_static_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response.class, cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>int32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 3;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeInt32(1, code_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(3, data_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response)) {
        return super.equals(obj);
      }
      cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response other = (cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response) obj;

      boolean result = true;
      result = result && (getCode()
          == other.getCode());
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && getData()
          .equals(other.getData());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Response)
        cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.internal_static_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.internal_static_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response.class, cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response.Builder.class);
      }

      // Construct using cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        code_ = 0;

        message_ = "";

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.internal_static_Response_descriptor;
      }

      public cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response getDefaultInstanceForType() {
        return cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response.getDefaultInstance();
      }

      public cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response build() {
        cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response buildPartial() {
        cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response result = new cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response(this);
        result.code_ = code_;
        result.message_ = message_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response) {
          return mergeFrom((cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response other) {
        if (other == cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int code_ ;
      /**
       * <code>int32 code = 1;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>int32 code = 1;</code>
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 code = 1;</code>
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 2;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 3;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 3;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 3;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Response)
    }

    // @@protoc_insertion_point(class_scope:Response)
    private static final cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response();
    }

    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    public cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ItemGetResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ItemGetResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ItemAsset itemAssets = 1;</code>
     */
    java.util.List<cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAsset> 
        getItemAssetsList();
    /**
     * <code>repeated .ItemAsset itemAssets = 1;</code>
     */
    cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAsset getItemAssets(int index);
    /**
     * <code>repeated .ItemAsset itemAssets = 1;</code>
     */
    int getItemAssetsCount();
    /**
     * <code>repeated .ItemAsset itemAssets = 1;</code>
     */
    java.util.List<? extends cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAssetOrBuilder> 
        getItemAssetsOrBuilderList();
    /**
     * <code>repeated .ItemAsset itemAssets = 1;</code>
     */
    cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAssetOrBuilder getItemAssetsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ItemGetResponse}
   */
  public  static final class ItemGetResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ItemGetResponse)
      ItemGetResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ItemGetResponse.newBuilder() to construct.
    private ItemGetResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ItemGetResponse() {
      itemAssets_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ItemGetResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                itemAssets_ = new java.util.ArrayList<cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAsset>();
                mutable_bitField0_ |= 0x00000001;
              }
              itemAssets_.add(
                  input.readMessage(cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAsset.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          itemAssets_ = java.util.Collections.unmodifiableList(itemAssets_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.internal_static_ItemGetResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.internal_static_ItemGetResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse.class, cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse.Builder.class);
    }

    public static final int ITEMASSETS_FIELD_NUMBER = 1;
    private java.util.List<cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAsset> itemAssets_;
    /**
     * <code>repeated .ItemAsset itemAssets = 1;</code>
     */
    public java.util.List<cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAsset> getItemAssetsList() {
      return itemAssets_;
    }
    /**
     * <code>repeated .ItemAsset itemAssets = 1;</code>
     */
    public java.util.List<? extends cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAssetOrBuilder> 
        getItemAssetsOrBuilderList() {
      return itemAssets_;
    }
    /**
     * <code>repeated .ItemAsset itemAssets = 1;</code>
     */
    public int getItemAssetsCount() {
      return itemAssets_.size();
    }
    /**
     * <code>repeated .ItemAsset itemAssets = 1;</code>
     */
    public cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAsset getItemAssets(int index) {
      return itemAssets_.get(index);
    }
    /**
     * <code>repeated .ItemAsset itemAssets = 1;</code>
     */
    public cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAssetOrBuilder getItemAssetsOrBuilder(
        int index) {
      return itemAssets_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < itemAssets_.size(); i++) {
        output.writeMessage(1, itemAssets_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < itemAssets_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, itemAssets_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse)) {
        return super.equals(obj);
      }
      cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse other = (cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse) obj;

      boolean result = true;
      result = result && getItemAssetsList()
          .equals(other.getItemAssetsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getItemAssetsCount() > 0) {
        hash = (37 * hash) + ITEMASSETS_FIELD_NUMBER;
        hash = (53 * hash) + getItemAssetsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ItemGetResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ItemGetResponse)
        cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.internal_static_ItemGetResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.internal_static_ItemGetResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse.class, cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse.Builder.class);
      }

      // Construct using cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getItemAssetsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (itemAssetsBuilder_ == null) {
          itemAssets_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          itemAssetsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.internal_static_ItemGetResponse_descriptor;
      }

      public cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse getDefaultInstanceForType() {
        return cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse.getDefaultInstance();
      }

      public cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse build() {
        cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse buildPartial() {
        cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse result = new cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse(this);
        int from_bitField0_ = bitField0_;
        if (itemAssetsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            itemAssets_ = java.util.Collections.unmodifiableList(itemAssets_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.itemAssets_ = itemAssets_;
        } else {
          result.itemAssets_ = itemAssetsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse) {
          return mergeFrom((cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse other) {
        if (other == cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse.getDefaultInstance()) return this;
        if (itemAssetsBuilder_ == null) {
          if (!other.itemAssets_.isEmpty()) {
            if (itemAssets_.isEmpty()) {
              itemAssets_ = other.itemAssets_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemAssetsIsMutable();
              itemAssets_.addAll(other.itemAssets_);
            }
            onChanged();
          }
        } else {
          if (!other.itemAssets_.isEmpty()) {
            if (itemAssetsBuilder_.isEmpty()) {
              itemAssetsBuilder_.dispose();
              itemAssetsBuilder_ = null;
              itemAssets_ = other.itemAssets_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemAssetsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getItemAssetsFieldBuilder() : null;
            } else {
              itemAssetsBuilder_.addAllMessages(other.itemAssets_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAsset> itemAssets_ =
        java.util.Collections.emptyList();
      private void ensureItemAssetsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          itemAssets_ = new java.util.ArrayList<cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAsset>(itemAssets_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAsset, cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAsset.Builder, cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAssetOrBuilder> itemAssetsBuilder_;

      /**
       * <code>repeated .ItemAsset itemAssets = 1;</code>
       */
      public java.util.List<cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAsset> getItemAssetsList() {
        if (itemAssetsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(itemAssets_);
        } else {
          return itemAssetsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ItemAsset itemAssets = 1;</code>
       */
      public int getItemAssetsCount() {
        if (itemAssetsBuilder_ == null) {
          return itemAssets_.size();
        } else {
          return itemAssetsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ItemAsset itemAssets = 1;</code>
       */
      public cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAsset getItemAssets(int index) {
        if (itemAssetsBuilder_ == null) {
          return itemAssets_.get(index);
        } else {
          return itemAssetsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ItemAsset itemAssets = 1;</code>
       */
      public Builder setItemAssets(
          int index, cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAsset value) {
        if (itemAssetsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemAssetsIsMutable();
          itemAssets_.set(index, value);
          onChanged();
        } else {
          itemAssetsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ItemAsset itemAssets = 1;</code>
       */
      public Builder setItemAssets(
          int index, cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAsset.Builder builderForValue) {
        if (itemAssetsBuilder_ == null) {
          ensureItemAssetsIsMutable();
          itemAssets_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemAssetsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ItemAsset itemAssets = 1;</code>
       */
      public Builder addItemAssets(cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAsset value) {
        if (itemAssetsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemAssetsIsMutable();
          itemAssets_.add(value);
          onChanged();
        } else {
          itemAssetsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ItemAsset itemAssets = 1;</code>
       */
      public Builder addItemAssets(
          int index, cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAsset value) {
        if (itemAssetsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemAssetsIsMutable();
          itemAssets_.add(index, value);
          onChanged();
        } else {
          itemAssetsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ItemAsset itemAssets = 1;</code>
       */
      public Builder addItemAssets(
          cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAsset.Builder builderForValue) {
        if (itemAssetsBuilder_ == null) {
          ensureItemAssetsIsMutable();
          itemAssets_.add(builderForValue.build());
          onChanged();
        } else {
          itemAssetsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ItemAsset itemAssets = 1;</code>
       */
      public Builder addItemAssets(
          int index, cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAsset.Builder builderForValue) {
        if (itemAssetsBuilder_ == null) {
          ensureItemAssetsIsMutable();
          itemAssets_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemAssetsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ItemAsset itemAssets = 1;</code>
       */
      public Builder addAllItemAssets(
          java.lang.Iterable<? extends cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAsset> values) {
        if (itemAssetsBuilder_ == null) {
          ensureItemAssetsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, itemAssets_);
          onChanged();
        } else {
          itemAssetsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ItemAsset itemAssets = 1;</code>
       */
      public Builder clearItemAssets() {
        if (itemAssetsBuilder_ == null) {
          itemAssets_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemAssetsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ItemAsset itemAssets = 1;</code>
       */
      public Builder removeItemAssets(int index) {
        if (itemAssetsBuilder_ == null) {
          ensureItemAssetsIsMutable();
          itemAssets_.remove(index);
          onChanged();
        } else {
          itemAssetsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ItemAsset itemAssets = 1;</code>
       */
      public cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAsset.Builder getItemAssetsBuilder(
          int index) {
        return getItemAssetsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ItemAsset itemAssets = 1;</code>
       */
      public cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAssetOrBuilder getItemAssetsOrBuilder(
          int index) {
        if (itemAssetsBuilder_ == null) {
          return itemAssets_.get(index);  } else {
          return itemAssetsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ItemAsset itemAssets = 1;</code>
       */
      public java.util.List<? extends cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAssetOrBuilder> 
           getItemAssetsOrBuilderList() {
        if (itemAssetsBuilder_ != null) {
          return itemAssetsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(itemAssets_);
        }
      }
      /**
       * <code>repeated .ItemAsset itemAssets = 1;</code>
       */
      public cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAsset.Builder addItemAssetsBuilder() {
        return getItemAssetsFieldBuilder().addBuilder(
            cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAsset.getDefaultInstance());
      }
      /**
       * <code>repeated .ItemAsset itemAssets = 1;</code>
       */
      public cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAsset.Builder addItemAssetsBuilder(
          int index) {
        return getItemAssetsFieldBuilder().addBuilder(
            index, cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAsset.getDefaultInstance());
      }
      /**
       * <code>repeated .ItemAsset itemAssets = 1;</code>
       */
      public java.util.List<cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAsset.Builder> 
           getItemAssetsBuilderList() {
        return getItemAssetsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAsset, cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAsset.Builder, cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAssetOrBuilder> 
          getItemAssetsFieldBuilder() {
        if (itemAssetsBuilder_ == null) {
          itemAssetsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAsset, cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAsset.Builder, cn.edu.nju.software.fabricservice.protomsg.Persistence.ItemAssetOrBuilder>(
                  itemAssets_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          itemAssets_ = null;
        }
        return itemAssetsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ItemGetResponse)
    }

    // @@protoc_insertion_point(class_scope:ItemGetResponse)
    private static final cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse();
    }

    public static cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ItemGetResponse>
        PARSER = new com.google.protobuf.AbstractParser<ItemGetResponse>() {
      public ItemGetResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ItemGetResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ItemGetResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ItemGetResponse> getParserForType() {
      return PARSER;
    }

    public cn.edu.nju.software.fabricservice.protomsg.ResponseOuterClass.ItemGetResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SimpleResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SimpleResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ItemGetResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ItemGetResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Response.proto\032\016Requests.proto\032\021Persis" +
      "tence.proto\"2\n\016SimpleResponse\022 \n\010request" +
      "s\030\001 \003(\0132\016.SimpleRequest\"7\n\010Response\022\014\n\004c" +
      "ode\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\022\014\n\004data\030\003 \001(\014" +
      "\"1\n\017ItemGetResponse\022\036\n\nitemAssets\030\001 \003(\0132" +
      "\n.ItemAssetB2\n*cn.edu.nju.software.fabri" +
      "cservice.protomsgZ\004mainb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cn.edu.nju.software.fabricservice.protomsg.Requests.getDescriptor(),
          cn.edu.nju.software.fabricservice.protomsg.Persistence.getDescriptor(),
        }, assigner);
    internal_static_SimpleResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SimpleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SimpleResponse_descriptor,
        new java.lang.String[] { "Requests", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "Code", "Message", "Data", });
    internal_static_ItemGetResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ItemGetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ItemGetResponse_descriptor,
        new java.lang.String[] { "ItemAssets", });
    cn.edu.nju.software.fabricservice.protomsg.Requests.getDescriptor();
    cn.edu.nju.software.fabricservice.protomsg.Persistence.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
